# Generated by Django 5.2.6 on 2025-09-17 15:16

import onboarding_ops.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProviderDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("BAA", "Business Associate Agreement"),
                            ("PURCHASE_AGREEMENT", "Purchase Agreement"),
                            ("MANUFACTURER_DOC", "Manufacturer Onboarding Document"),
                            ("PROVIDER_REVIEW_DOC", "Provider Review Request Docs"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=onboarding_ops.models.document_upload_path
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProviderForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form_type", models.CharField(blank=True, max_length=100, null=True)),
                ("completed", models.BooleanField(default=False)),
                (
                    "completed_form",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=onboarding_ops.models.provider_upload_path,
                    ),
                ),
                ("form_data", models.JSONField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
