# Generated by Django 5.2 on 2025-09-23 02:45

import django.db.models.deletion
import onboarding_ops.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0008_patient_wound_size_length_patient_wound_size_width"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("PROVIDER_REVIEW_DOC", "Provider Review Request Docs"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Type of document, e.g., BAA, License.",
                        max_length=50,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="The uploaded document file.",
                        upload_to=onboarding_ops.models.provider_document_upload_path,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider Document",
                "verbose_name_plural": "Provider Documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ProviderForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_type",
                    models.CharField(
                        help_text="e.g., 'New Account Form', 'IVR Report'",
                        max_length=100,
                    ),
                ),
                (
                    "submission_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique ID from an external system like Jotform.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "completed_form",
                    models.FileField(
                        blank=True,
                        help_text="The completed PDF file.",
                        null=True,
                        upload_to=onboarding_ops.models.provider_form_upload_path,
                    ),
                ),
                (
                    "form_data",
                    models.JSONField(
                        blank=True,
                        help_text="Snapshot of the form's data at the time of submission.",
                        null=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_forms",
                        to="patients.patient",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_forms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider Form",
                "verbose_name_plural": "Provider Forms",
                "ordering": ["-date_created"],
            },
        ),
    ]
