# Generated by Django 5.2 on 2025-08-07 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_ops', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerform',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providerform',
            name='form_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='providerform',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='patients.patient'),
        ),
    ]
