# Generated by Django 5.2 on 2025-09-06 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_remove_product_price_productvariant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="price",
        ),
    ]
