# Generated by Django 5.2 on 2025-09-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_remove_productvariant_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="max_size",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
