# Generated by Django 5.2 on 2025-09-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_productvariant_max_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="max_size",
        ),
        migrations.AddField(
            model_name="product",
            name="max_size",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
