# Generated by Django 5.2 on 2025-09-09 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_remove_productvariant_max_size_product_max_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="max_size",
        ),
    ]
