# Generated by Django 5.2 on 2025-09-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_remove_product_max_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="max_size",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
