# Generated by Django 5.2 on 2025-08-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rep', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrep',
            name='Representative Email Address',
        ),
        migrations.RemoveField(
            model_name='salesrep',
            name='Representative Name',
        ),
        migrations.RemoveField(
            model_name='salesrep',
            name='Representative Phone Number',
        ),
        migrations.AddField(
            model_name='salesrep',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Representative Email Address'),
        ),
        migrations.AddField(
            model_name='salesrep',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Representative Name'),
        ),
        migrations.AddField(
            model_name='salesrep',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Representative Phone Number'),
        ),
    ]
