# Generated by Django 5.2 on 2025-09-23 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_rep", "0002_remove_salesrep_representative_email_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="salesrep",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salesrep_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
