# Generated by Django 5.2.6 on 2025-09-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("body", models.TextField()),
                (
                    "document",
                    models.FileField(blank=True, null=True, upload_to="notes_docs/"),
                ),
            ],
        ),
    ]
