# Generated by Django 5.2 on 2025-08-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='notes_docs/'),
        ),
    ]
