# Generated by Django 5.2 on 2025-07-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_auth', '0002_user_is_verified_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification_code',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
