# Generated by Django 5.2 on 2025-08-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_auth', '0004_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ivrStatus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
