# Generated by Django 5.2 on 2025-08-05 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider_auth', '0005_patient_ivrstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
