# Generated by Django 5.2 on 2025-08-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_auth', '0007_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
