# Generated by Django 5.2 on 2025-08-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_auth', '0008_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facility',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='facility_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Primary Care Provider', 'Primary Care Provider'), ('Nurse', 'Nurse'), ('Administrator', 'Administrator'), ('Medical Supply Technicians', 'Medical Supply Technicians')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, default='/media/images/default_user.jpg', null=True, upload_to='images'),
        ),
    ]
