# Generated by Django 5.2 on 2025-08-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_auth', '0009_user_facility_user_facility_phone_number_user_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='user',
            name='facility_phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='profile',
            name='facility',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='facility_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('Primary Care Provider', 'Primary Care Provider'), ('Nurse', 'Nurse'), ('Administrator', 'Administrator'), ('Medical Supply Technician', 'Medical Supply Technician')], max_length=200, null=True),
        ),
    ]
