# Generated by Django 5.2 on 2025-08-14 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_auth', '0010_remove_user_facility_and_more'),
        ('sales_rep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sales_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='sales_rep.salesrep'),
        ),
    ]
