# Generated by Django 5.2 on 2025-08-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_auth', '0011_profile_sales_rep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, default='https://promedhealthplus.blob.core.windows.net/media/images/default_user.jpg', null=True, upload_to='images'),
        ),
    ]
