# Generated by Django 5.2 on 2025-08-20 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider_auth', '0012_remove_user_full_name_alter_profile_image 2'),
        ('provider_auth', '0012_remove_user_full_name_alter_profile_image'),
    ]

    operations = [
    ]
