# Generated by Django 5.2 on 2025-08-25 03:03

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provider_auth", "0013_merge_20250820_2122"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country_code",
            field=models.CharField(
                choices=[("+93", "Afghanistan")],
                default="+1",
                help_text="Default country code is +1 (US).",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.FileField(
                blank=True,
                default="/media/images/default_user.jpg",
                null=True,
                upload_to="images",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
    ]
