# Generated by Django 5.2 on 2025-08-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "provider_auth",
            "0014_user_country_code_user_full_name_alter_profile_image_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="country_code",
            field=models.CharField(
                choices=[
                    ("+1", "United States"),
                    ("+1", "Canada"),
                    ("+44", "United Kingdom"),
                    ("+33", "France"),
                    ("+39", "Italy"),
                    ("+49", "Germany"),
                    ("+34", "Spain"),
                ],
                default="+1",
                help_text="Default country code is +1 (US).",
                max_length=5,
            ),
        ),
    ]
