# Generated by Django 5.2 on 2025-08-27 01:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provider_auth", "0015_alter_user_country_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.FileField(
                blank=True, default="default_user.jpg", null=True, upload_to="images"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="country_code",
            field=models.CharField(
                choices=[
                    ("+1", "United States"),
                    ("+1", "Canada"),
                    ("+44", "United Kingdom"),
                    ("+33", "France"),
                    ("+39", "Italy"),
                    ("+49", "Germany"),
                    ("+34", "Spain"),
                ],
                default="+1",
                help_text="Country dial code for reference (e.g. +1 for US).",
                max_length=5,
            ),
        ),
        migrations.CreateModel(
            name="EmailVerificationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
