# Generated by Django 5.2 on 2025-08-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provider_auth", "0016_alter_profile_image_alter_user_country_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.FileField(
                blank=True,
                default="images/default_user.jpg",
                null=True,
                upload_to="images",
            ),
        ),
    ]
