# Generated by Django 5.2 on 2025-09-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provider_auth", "0018_passwordresettoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="npi_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
