# Generated by Django 5.2.6 on 2025-09-11 13:40

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                (
                    "middle_initial",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=20, null=True, region=None
                    ),
                ),
                (
                    "primary_insurance",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "primary_insurance_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "secondary_insurance",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "secondary_insurance_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "tertiary_insurance",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tertiary_insurance_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "medical_record_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "ivrStatus",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Denied", "Denied"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
