# Generated by Django 5.2.6 on 2025-09-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="woundSizeLength",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="woundSizeWidth",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
