# Generated by Django 5.2.6 on 2025-09-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="activate_Account",
            field=models.CharField(
                blank=True,
                choices=[("Activated", "Activated"), ("Deactivated", "Deactivated")],
                max_length=50,
                null=True,
            ),
        ),
    ]
