# Generated by Django 5.2 on 2025-08-08 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='primary_insurance_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='secondary_insurance_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='tertiary_insurance_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
