# Generated by Django 5.2.6 on 2025-09-11 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_patient_woundsizelength_patient_woundsizewidth"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="ivrStatus",
            new_name="ivr_status",
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="woundSizeLength",
            new_name="wound_size_length",
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="woundSizeWidth",
            new_name="wound_size_width",
        ),
    ]
