# Generated by Django 5.2.6 on 2025-09-11 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_rename_ivrstatus_patient_ivr_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="ivr_status",
            new_name="ivrStatus",
        ),
    ]
