# Generated by Django 5.2 on 2025-08-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patient_ivrstatus'),
        ('patients', '0005_alter_patient_provider'),
    ]

    operations = [
    ]
