# Generated by Django 5.2 on 2025-08-20 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patient_provider 2'),
        ('patients', '0006_merge_20250820_1358'),
    ]

    operations = [
    ]
