# Generated by Django 5.2 on 2025-09-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0007_merge_20250820_2123"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="wound_size_length",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="wound_size_width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
