# Generated by Django 5.2 on 2025-09-01 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="mft_price",
            new_name="price_at_order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="manufacturer",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product_name",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ordered_items",
                to="product.product",
            ),
        ),
    ]
