# Generated by Django 5.2 on 2025-09-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_rename_mft_price_orderitem_price_at_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
