# Generated by Django 5.2 on 2025-09-03 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_country"),
        ("product", "0002_remove_product_price_productvariant"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="product.productvariant",
            ),
        ),
        migrations.AlterModelTable(
            name="orderitem",
            table="order_items",
        ),
    ]
