# Generated by Django 5.2 on 2025-09-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_remove_order_total_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="max_size",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
