# Generated by Django 5.2 on 2025-09-06 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_orderitem_max_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="max_size",
        ),
    ]
